baseURL: "https://blog.thecraftingstrider.net/"
title: "The Crafting Strider"
theme: "kiera"

enableEmoji: true

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage: "en" # Default language to use

languages:
  en:
    weight: 1
    languageCode: "en"
    languageName: "en"
    menu:
      main:
        - name: "Home"
          weight: 10
          pageRef: /
        - name: "Posts"
          weight: 20
          pageRef: /posts
        - name: "Tags"
          weight: 30
          pageRef: /tags
        - name: "About"
          weight: 40
          pageRef: /about
  be:
    weight: 2
    languageCode: "be"
    languageName: "be"
    title: "The Crafting Strider"
    params:
      tagline: "Асабісты блог Рамана Бут-Гусаіма. Думкі і тэхнічныя публікацыі з жыцця распрацоўшчыка праграмнага забеспячэння"
      description: "Асабісты блог Рамана Бут-Гусаіма"
    menu:
      main:
        - name: "Хатняя"
          weight: 10
          pageRef: /
        - name: "Публікацыі"
          weight: 20
          pageRef: /posts
        - name: "Цэтлікі"
          weight: 30
          pageRef: /tags
        - name: "Аб аўтары"
          weight: 40
          pageRef: /about

author:
  name: "Raman But-Husaim"
  github: "RamanBut-Husaim"
  linkedin: "raman-b-208093ab"

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

params:
  tagline: "Raman But-Husaim's personal webblog. Ideas, tech articles born through the life of a software engineer"
  description: "Raman But-Husaim's personal webblog"
  favicon: "/favicon.ico"
  customCSS: ["css/custom.css"]
  openGraph:
    description: "Raman But-Husaim's personal webblog"
    image: "/about/avatar.jpg"
