account_id = "b138d2341f0cb1ff2160762e647f1621"
name = "blog-thecraftingstrider"
type = "webpack"
workers_dev = true

[site]
bucket = "./public"
entry-point = "workers-site"

[env.staging]
name = "blog-thecraftingstrider-stg"

[env.production]
workers_dev = false
name = "blog-thecraftingstrider-prd"
zone_id = "62e04a3c74006a1fe79e4cb3f915436d"
route = "blog.thecraftingstrider.net/*"
